#!/usr/bin/env ruby

require File.join(File.dirname(__FILE__), 'vocabulary-chest' )

def get_text
	if !ARGV.empty?
		text = ""
		ARGV.each {|filename|
			text += File.open(filename, 'r'){|file| file.read}
		}
		text
	else
		STDIN.read
	end
end

def ask word, index, words
		answer = ''
		while !['y','n'].include?(answer)
			puts 
			puts "- #{word}"
			puts "> Do you know this word? [y or n] (#{index + 1} of #{words.size})"

			answer = STDIN.gets.gsub(/[\r\n]/, '')
		end
		answer
end

def collect_words_from textual_words
	textual_words.reject!{|w|VocabularyChest::is_known?(w)}
	textual_words.reject!{|w|VocabularyChest::contains?(w)} if @@options.include? "-n"

	words_by_stem = textual_words.inject({}){|hash, w| hash[VocabularyChest::stem w] = w; hash}
	words_by_stem.reject!{|s,w| (s =~ /^[-\d\s,\.]*$/) == 0}

	words_by_stem.values
end

if __FILE__ == $0
	@@options = ARGV.select{|arg| ["-n"].include? arg}
	ARGV.reject!{|arg| @@options.include? arg}

	text = get_text
	textual_words = text.split(" ").collect{|w| w.chomp}
	puts "Thanks. Please wait..."

	words = collect_words_from textual_words
	words.each_with_index {|word, index|
    answer = ask word, index, words
		VocabularyChest::add_to_known_words(word) if answer == 'y'
		VocabularyChest::add_to_unknown_words(word) if answer == 'n'
	}

	puts "Done."
end
