#!/usr/bin/env ruby

def fetch_definition word
	definitions = `dict "#{word}" 2>/dev/null | grep '     ' | head -2`.chomp.gsub("     ","").split(/[\r\n]/)
	definitions.uniq.join(" -- ")
end

def sanitize word
	word.gsub(/[,\.]/,"")
end

def go words
	words.map{|w| sanitize w}.each{|w| puts "#{w}: #{fetch_definition w}"}
end

if __FILE__ == $0
	if !ARGV.empty?
		go ARGV
	else
		go STDIN.read.split("\n")
	end
end
