#!/usr/bin/env ruby

require File.join(File.dirname(__FILE__), 'document-cache' )

count = 1
count_param = ARGV.find{|a| (a =~ /--\d*/) == 0}
if !count_param.nil?
	count = count_param.sub("--","").to_i
	ARGV.reject!{|a| a == count_param}
end

search = ARGV.join(" ")
matches = DocumentCache.find_examples_for search, count
exit(1) if matches.empty?
puts matches.join("\n--\n")
