#!/usr/bin/env ruby

module Lookup

	def self.fetch_definition word
		definitions = `dict "#{word}" 2>/dev/null | grep '     ' | head -2`.chomp.gsub("     ","").split(/[\r\n]/)
		definitions.uniq.join(" -- ")
	end

	def self.sanitize word
		word.gsub(/[,\.]/,"")
	end

	def self.go words
		words.map{|w| sanitize w}.map{|w| "#{w}: #{fetch_definition w}"}.join("\n")
	end
end

if __FILE__ == $0
	if !ARGV.empty?
		puts Lookup::go ARGV
	else
		puts Lookup::go STDIN.read.split("\n")
	end
end
