#!/usr/bin/env ruby

require File.join(File.dirname(__FILE__), 'vocabulary-chest' )
load File.join(File.dirname(__FILE__), 'lookup' )

def analyse text
	words = text.split(" ")
	known = words.select{|w| VocabularyChest.is_known? w}
	unknown = (words - known)
	return [known.map{|w| VocabularyChest::sanitize w}.uniq, unknown.map{|w| VocabularyChest::sanitize w}.uniq]
end

def output options
	known, unknown = options
	size = known.size + unknown.size
	
	puts
	puts "--"
	puts "UNKNOWN WORDS: #{unknown.join(", ")}"
	puts 
	puts "DEFINITIONS"
	puts Lookup::go(unknown)
	puts "--"
	puts
	puts "Total number of unknown words: #{unknown.size}"
	puts "Total number of known words: #{known.size}"
	puts "Total number of words: #{size}"
	puts "Percentage of words known: #{'%.2f' % (known.size.to_f / size * 100)}%"
end

if __FILE__ == $0
	if !ARGV.empty?
		ARGV.each {|filename|
			text = File.open(filename,'r'){|file| file.read}
			puts "#{filename}:"
			output(analyse(text))
		}
	else
		text = STDIN.read
		output(analyse(text))
	end
end

