#!/usr/bin/env ruby

require File.join(File.dirname(__FILE__), 'document-cache' )
require File.join(File.dirname(__FILE__), 'vocabulary-chest' )
require File.join(File.dirname(__FILE__), 'game' )

if __FILE__ == $0
	def get_input
		if !ARGV.empty?
			File.open(ARGV[0]){|f| f.read}
		else
			STDIN.read
		end
	end

	input = get_input
	words = input.split("\n")
	words.reject!{|w| DocumentCache.find_examples_for(w).empty?}

	Game.new.play(words){ |word|
		matches = DocumentCache.find_examples_for(word, 10).keys
		sentence = matches.sort{|a, b| a.size <=> b.size}.first
		correct_answer = DocumentCache::extract_matching_words(word, sentence).first
		[sentence, correct_answer]
	}
end
